## 반복문을 통한 데이터 프레임 접근하기
- 반복문에 들어가는 값
- 반복문을 통하여 나오는 값

In [1]:
for i in range(5):
    print(i)

0
1
2
3
4

- range는 range(5)라는 숫자가 나옴.
- in 뒤에는 range함수와 시퀀스 객체에 따라 값이 달라진다.

In [2]:
a = ['버섯','소고기','돼지고기','김치','쌀']

In [3]:
for i in a:
    print(i)

버섯
소고기
돼지고기
김치
쌀

- 시퀀스 객체 등으로 range가 아닌 다른 것으로 끝나게 될 경우, 시퀀스 객체 안에 값을 가지고 오게 된다.
- 시퀀스 객체를 range()를 이용하여 표현하기

In [5]:
for i in range(len(a)):
    print(a[i])

버섯
소고기
돼지고기
김치
쌀

## 데이터프레임 접근하는 방법
- 데이터프레임은 행과 열로 이루어져 있음
- 2차원임

In [6]:
import pandas as pd

In [7]:
df = pd.DataFrame({'음식':["스테이크","파스타","마파두부","찜닭"],
                  '코스트':[900,600,500,500]})

In [8]:
df

     음식  코스트
0  스테이크  900
1   파스타  600
2  마파두부  500
3    찜닭  500

In [9]:
df.columns #컬럼을 보는 법

Index(['음식', '코스트'], dtype='object')

In [10]:
df.index #인덱스 보는 법

RangeIndex(start=0, stop=4, step=1)

In [12]:
df['음식']

0    스테이크
1     파스타
2    마파두부
3      찜닭
Name: 음식, dtype: object

In [13]:
df.iloc[1]

음식     파스타
코스트    600
Name: 1, dtype: object

In [14]:
df.iloc[3]

음식      찜닭
코스트    500
Name: 3, dtype: object

## 반복문으로 데이터프레임 접근하면 어떤 식일까?

In [15]:
for i in df:
    print(i)

음식
코스트

In [16]:
df['음식']

0    스테이크
1     파스타
2    마파두부
3      찜닭
Name: 음식, dtype: object

In [18]:
for i in df['음식']:
    print(i)

스테이크
파스타
마파두부
찜닭

In [19]:
for i in range(len(df['음식'])):
    print(df.음식[i])

스테이크
파스타
마파두부
찜닭

인덱스로 접근하기

In [22]:
for i in range(len(df)):
    print(df.음식.loc[i])
    
for i in range(len(df)):
    print(df.음식.iloc[i])

스테이크
파스타
마파두부
찜닭
스테이크
파스타
마파두부
찜닭

In [24]:
mpg = pd.read_csv('mpg.csv')

In [25]:
mpg

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,category
0,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact
1,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact
2,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact
3,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact
4,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact
...,...,...,...,...,...,...,...,...,...,...,...
229,volkswagen,passat,2.0,2008,4,auto(s6),f,19,28,p,midsize
230,volkswagen,passat,2.0,2008,4,manual(m6),f,21,29,p,midsize
231,volkswagen,passat,2.8,1999,6,auto(l5),f,16,26,p,midsize
232,volkswagen,passat,2.8,1999,6,manual(m5),f,18,26,p,midsize
233,volkswagen,passat,3.6,2008,6,auto(s6),f,17,26,p,midsize

In [26]:
for i in mpg.model:
    print(i)

a4
a4
a4
a4
a4
a4
a4
a4 quattro
a4 quattro
a4 quattro
a4 quattro
a4 quattro
a4 quattro
a4 quattro
a4 quattro
a6 quattro
a6 quattro
a6 quattro
c1500 suburban 2wd
c1500 suburban 2wd
c1500 suburban 2wd
c1500 suburban 2wd
c1500 suburban 2wd
corvette
corvette
corvette
corvette
corvette
k1500 tahoe 4wd
k1500 tahoe 4wd
k1500 tahoe 4wd
k1500 tahoe 4wd
malibu
malibu
malibu
malibu
malibu
caravan 2wd
caravan 2wd
caravan 2wd
caravan 2wd
caravan 2wd
caravan 2wd
caravan 2wd
caravan 2wd
caravan 2wd
caravan 2wd
caravan 2wd
dakota pickup 4wd
dakota pickup 4wd
dakota pickup 4wd
dakota pickup 4wd
dakota pickup 4wd
dakota pickup 4wd
dakota pickup 4wd
dakota pickup 4wd
dakota pickup 4wd
durango 4wd
durango 4wd
durango 4wd
durango 4wd
durango 4wd
durango 4wd
durango 4wd
ram 1500 pickup 4wd
ram 1500 pickup 4wd
ram 1500 pickup 4wd
ram 1500 pickup 4wd
ram 1500 pickup 4wd
ram 1500 pickup 4wd
ram 1500 pickup 4wd
ram 1500 pickup 4wd
ram 1500 pickup 4wd
ram 1500 pickup 4wd
expedition 2wd
expedition 2wd
expedition 2wd
explorer 4wd
explorer 4wd
explorer 4wd
explorer 4wd
explorer 4wd
explorer 4wd
f150 pickup 4wd
f150 pickup 4wd
f150 pickup 4wd
f150 pickup 4wd
f150 pickup 4wd
f150 pickup 4wd
f150 pickup 4wd
mustang
mustang
mustang
mustang
mustang
mustang
mustang
mustang
mustang
civic
civic
civic
civic
civic
civic
civic
civic
civic
sonata
sonata
sonata
sonata
sonata
sonata
sonata
tiburon
tiburon
tiburon
tiburon
tiburon
tiburon
tiburon
grand cherokee 4wd
grand cherokee 4wd
grand cherokee 4wd
grand cherokee 4wd
grand cherokee 4wd
grand cherokee 4wd
grand cherokee 4wd
grand cherokee 4wd
range rover
range rover
range rover
range rover
navigator 2wd
navigator 2wd
navigator 2wd
mountaineer 4wd
mountaineer 4wd
mountaineer 4wd
mountaineer 4wd
altima
altima
altima
altima
altima
altima
maxima
maxima
maxima
pathfinder 4wd
pathfinder 4wd
pathfinder 4wd
pathfinder 4wd
grand prix
grand prix
grand prix
grand prix
grand prix
forester awd
forester awd
forester awd
forester awd
forester awd
forester awd
impreza awd
impreza awd
impreza awd
impreza awd
impreza awd
impreza awd
impreza awd
impreza awd
4runner 4wd
4runner 4wd
4runner 4wd
4runner 4wd
4runner 4wd
4runner 4wd
camry
camry
camry
camry
camry
camry
camry
camry solara
camry solara
camry solara
camry solara
camry solara
camry solara
camry solara
corolla
corolla
corolla
corolla
corolla
land cruiser wagon 4wd
land cruiser wagon 4wd
toyota tacoma 4wd
toyota tacoma 4wd
toyota tacoma 4wd
toyota tacoma 4wd
toyota tacoma 4wd
toyota tacoma 4wd
toyota tacoma 4wd
gti
gti
gti
gti
gti
jetta
jetta
jetta
jetta
jetta
jetta
jetta
jetta
jetta
new beetle
new beetle
new beetle
new beetle
new beetle
new beetle
passat
passat
passat
passat
passat
passat
passat

In [27]:
for j in mpg.trans:
    print(j)

auto(l5)
manual(m5)
manual(m6)
auto(av)
auto(l5)
manual(m5)
auto(av)
manual(m5)
auto(l5)
manual(m6)
auto(s6)
auto(l5)
manual(m5)
auto(s6)
manual(m6)
auto(l5)
auto(s6)
auto(s6)
auto(l4)
auto(l4)
auto(l4)
auto(l4)
auto(l4)
manual(m6)
auto(l4)
manual(m6)
auto(s6)
manual(m6)
auto(l4)
auto(l4)
auto(l4)
auto(l4)
auto(l4)
auto(l4)
auto(l4)
auto(l4)
auto(s6)
auto(l3)
auto(l4)
auto(l4)
auto(l4)
auto(l4)
auto(l4)
auto(l4)
auto(l4)
auto(l4)
auto(l6)
auto(l6)
manual(m6)
auto(l4)
auto(l4)
manual(m5)
auto(l5)
auto(l5)
auto(l5)
manual(m5)
auto(l4)
auto(l4)
auto(l5)
auto(l5)
auto(l5)
auto(l4)
auto(l5)
auto(l4)
manual(m6)
auto(l5)
auto(l5)
auto(l5)
manual(m6)
manual(m6)
auto(l4)
manual(m5)
auto(l5)
auto(l4)
auto(l4)
auto(l4)
auto(l6)
auto(l5)
manual(m5)
auto(l5)
auto(l5)
auto(l6)
auto(l4)
auto(l4)
manual(m5)
manual(m5)
auto(l4)
auto(l4)
auto(l4)
auto(l4)
manual(m5)
auto(l4)
manual(m5)
auto(l5)
auto(l4)
manual(m5)
manual(m5)
auto(l5)
manual(m6)
manual(m5)
auto(l4)
manual(m5)
manual(m5)
auto(l4)
manual(m5)
auto(l5)
auto(l5)
manual(m6)
auto(l4)
manual(m5)
auto(l4)
manual(m5)
auto(l4)
manual(m5)
auto(l5)
auto(l4)
manual(m5)
manual(m5)
auto(l4)
auto(l4)
manual(m6)
manual(m5)
auto(l5)
auto(l5)
auto(l4)
auto(l4)
auto(l5)
auto(l5)
auto(l5)
auto(l5)
auto(l4)
auto(s6)
auto(s6)
auto(l4)
auto(l4)
auto(l4)
auto(l6)
auto(l5)
auto(l5)
auto(l6)
auto(l4)
manual(m5)
auto(l4)
auto(av)
manual(m6)
manual(m6)
auto(av)
auto(l4)
manual(m5)
auto(av)
auto(l4)
manual(m5)
auto(l5)
auto(s5)
auto(l4)
auto(l4)
auto(l4)
auto(l4)
auto(s4)
manual(m5)
auto(l4)
manual(m5)
manual(m5)
auto(l4)
auto(l4)
auto(l4)
manual(m5)
manual(m5)
auto(l4)
auto(s4)
auto(s4)
manual(m5)
manual(m5)
manual(m5)
auto(l4)
auto(l4)
manual(m5)
auto(l5)
auto(l5)
manual(m5)
auto(l4)
manual(m5)
auto(l5)
auto(l4)
manual(m5)
auto(s6)
auto(l4)
manual(m5)
manual(m5)
auto(s5)
auto(l4)
manual(m5)
auto(s5)
auto(l3)
auto(l4)
manual(m5)
manual(m5)
auto(l4)
auto(l4)
auto(s6)
manual(m5)
auto(l4)
manual(m5)
manual(m5)
auto(l4)
manual(m6)
auto(l5)
manual(m5)
auto(l4)
manual(m6)
auto(s6)
manual(m5)
manual(m5)
manual(m5)
auto(l4)
auto(s6)
manual(m6)
auto(s6)
manual(m5)
auto(l4)
manual(m5)
manual(m5)
auto(l4)
manual(m5)
auto(l4)
manual(m5)
auto(s6)
manual(m5)
auto(l5)
auto(s6)
manual(m6)
auto(l5)
manual(m5)
auto(s6)

In [30]:
for a, b, c in zip(mpg.cty, mpg.displ, mpg.manufacturer):
    print(a,b,c)

18 1.8 audi
21 1.8 audi
20 2.0 audi
21 2.0 audi
16 2.8 audi
18 2.8 audi
18 3.1 audi
18 1.8 audi
16 1.8 audi
20 2.0 audi
19 2.0 audi
15 2.8 audi
17 2.8 audi
17 3.1 audi
15 3.1 audi
15 2.8 audi
17 3.1 audi
16 4.2 audi
14 5.3 chevrolet
11 5.3 chevrolet
14 5.3 chevrolet
13 5.7 chevrolet
12 6.0 chevrolet
16 5.7 chevrolet
15 5.7 chevrolet
16 6.2 chevrolet
15 6.2 chevrolet
15 7.0 chevrolet
14 5.3 chevrolet
11 5.3 chevrolet
11 5.7 chevrolet
14 6.5 chevrolet
19 2.4 chevrolet
22 2.4 chevrolet
18 3.1 chevrolet
18 3.5 chevrolet
17 3.6 chevrolet
18 2.4 dodge
17 3.0 dodge
16 3.3 dodge
16 3.3 dodge
17 3.3 dodge
17 3.3 dodge
11 3.3 dodge
15 3.8 dodge
15 3.8 dodge
16 3.8 dodge
16 4.0 dodge
15 3.7 dodge
14 3.7 dodge
13 3.9 dodge
14 3.9 dodge
14 4.7 dodge
14 4.7 dodge
9 4.7 dodge
11 5.2 dodge
11 5.2 dodge
13 3.9 dodge
13 4.7 dodge
9 4.7 dodge
13 4.7 dodge
11 5.2 dodge
13 5.7 dodge
11 5.9 dodge
12 4.7 dodge
9 4.7 dodge
13 4.7 dodge
13 4.7 dodge
12 4.7 dodge
9 4.7 dodge
11 5.2 dodge
11 5.2 dodge
13 5.7 dodge
11 5.9 dodge
11 4.6 ford
11 5.4 ford
12 5.4 ford
14 4.0 ford
15 4.0 ford
14 4.0 ford
13 4.0 ford
13 4.6 ford
13 5.0 ford
14 4.2 ford
14 4.2 ford
13 4.6 ford
13 4.6 ford
13 4.6 ford
11 5.4 ford
13 5.4 ford
18 3.8 ford
18 3.8 ford
17 4.0 ford
16 4.0 ford
15 4.6 ford
15 4.6 ford
15 4.6 ford
15 4.6 ford
14 5.4 ford
28 1.6 honda
24 1.6 honda
25 1.6 honda
23 1.6 honda
24 1.6 honda
26 1.8 honda
25 1.8 honda
24 1.8 honda
21 2.0 honda
18 2.4 hyundai
18 2.4 hyundai
21 2.4 hyundai
21 2.4 hyundai
18 2.5 hyundai
18 2.5 hyundai
19 3.3 hyundai
19 2.0 hyundai
19 2.0 hyundai
20 2.0 hyundai
20 2.0 hyundai
17 2.7 hyundai
16 2.7 hyundai
17 2.7 hyundai
17 3.0 jeep
15 3.7 jeep
15 4.0 jeep
14 4.7 jeep
9 4.7 jeep
14 4.7 jeep
13 5.7 jeep
11 6.1 jeep
11 4.0 land rover
12 4.2 land rover
12 4.4 land rover
11 4.6 land rover
11 5.4 lincoln
11 5.4 lincoln
12 5.4 lincoln
14 4.0 mercury
13 4.0 mercury
13 4.6 mercury
13 5.0 mercury
21 2.4 nissan
19 2.4 nissan
23 2.5 nissan
23 2.5 nissan
19 3.5 nissan
19 3.5 nissan
18 3.0 nissan
19 3.0 nissan
19 3.5 nissan
14 3.3 nissan
15 3.3 nissan
14 4.0 nissan
12 5.6 nissan
18 3.1 pontiac
16 3.8 pontiac
17 3.8 pontiac
18 3.8 pontiac
16 5.3 pontiac
18 2.5 subaru
18 2.5 subaru
20 2.5 subaru
19 2.5 subaru
20 2.5 subaru
18 2.5 subaru
21 2.2 subaru
19 2.2 subaru
19 2.5 subaru
19 2.5 subaru
20 2.5 subaru
20 2.5 subaru
19 2.5 subaru
20 2.5 subaru
15 2.7 toyota
16 2.7 toyota
15 3.4 toyota
15 3.4 toyota
16 4.0 toyota
14 4.7 toyota
21 2.2 toyota
21 2.2 toyota
21 2.4 toyota
21 2.4 toyota
18 3.0 toyota
18 3.0 toyota
19 3.5 toyota
21 2.2 toyota
21 2.2 toyota
21 2.4 toyota
22 2.4 toyota
18 3.0 toyota
18 3.0 toyota
18 3.3 toyota
24 1.8 toyota
24 1.8 toyota
26 1.8 toyota
28 1.8 toyota
26 1.8 toyota
11 4.7 toyota
13 5.7 toyota
15 2.7 toyota
16 2.7 toyota
17 2.7 toyota
15 3.4 toyota
15 3.4 toyota
15 4.0 toyota
16 4.0 toyota
21 2.0 volkswagen
19 2.0 volkswagen
21 2.0 volkswagen
22 2.0 volkswagen
17 2.8 volkswagen
33 1.9 volkswagen
21 2.0 volkswagen
19 2.0 volkswagen
22 2.0 volkswagen
21 2.0 volkswagen
21 2.5 volkswagen
21 2.5 volkswagen
16 2.8 volkswagen
17 2.8 volkswagen
35 1.9 volkswagen
29 1.9 volkswagen
21 2.0 volkswagen
19 2.0 volkswagen
20 2.5 volkswagen
20 2.5 volkswagen
21 1.8 volkswagen
18 1.8 volkswagen
19 2.0 volkswagen
21 2.0 volkswagen
16 2.8 volkswagen
18 2.8 volkswagen
17 3.6 volkswagen

In [32]:
i = []
j = []
k = []

for a, b, c in zip(mpg.cty, mpg.displ, mpg.manufacturer):
    i.append(a)
    j.append(b)
    k.append(c)
    
print(k)

['audi', 'audi', 'audi', 'audi', 'audi', 'audi', 'audi', 'audi', 'audi', 'audi', 'audi', 'audi', 'audi', 'audi', 'audi', 'audi', 'audi', 'audi', 'chevrolet', 'chevrolet', 'chevrolet', 'chevrolet', 'chevrolet', 'chevrolet', 'chevrolet', 'chevrolet', 'chevrolet', 'chevrolet', 'chevrolet', 'chevrolet', 'chevrolet', 'chevrolet', 'chevrolet', 'chevrolet', 'chevrolet', 'chevrolet', 'chevrolet', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'honda', 'honda', 'honda', 'honda', 'honda', 'honda', 'honda', 'honda', 'honda', 'hyundai', 'hyundai', 'hyundai', 'hyundai', 'hyundai', 'hyundai', 'hyundai', 'hyundai', 'hyundai', 'hyundai', 'hyundai', 'hyundai', 'hyundai', 'hyundai', 'jeep', 'jeep', 'jeep', 'jeep', 'jeep', 'jeep', 'jeep', 'jeep', 'land rover', 'land rover', 'land rover', 'land rover', 'lincoln', 'lincoln', 'lincoln', 'mercury', 'mercury', 'mercury', 'mercury', 'nissan', 'nissan', 'nissan', 'nissan', 'nissan', 'nissan', 'nissan', 'nissan', 'nissan', 'nissan', 'nissan', 'nissan', 'nissan', 'pontiac', 'pontiac', 'pontiac', 'pontiac', 'pontiac', 'subaru', 'subaru', 'subaru', 'subaru', 'subaru', 'subaru', 'subaru', 'subaru', 'subaru', 'subaru', 'subaru', 'subaru', 'subaru', 'subaru', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen']

In [37]:
mpg.year.mean()

2003.5

### mpg 데이터 중 model, hwy 중에서 hwy가 23.4 이상인 친구들만 반복문으로 가지고 오기!

- 수치형 데이터를 if 문으로 만들어서 조건을 걸어준다.

In [38]:
for i, j in zip(mpg.model, mpg.year):
    if j >= 2003.5:
        print(i,j)

a4 2008
a4 2008
a4 2008
a4 quattro 2008
a4 quattro 2008
a4 quattro 2008
a4 quattro 2008
a6 quattro 2008
a6 quattro 2008
c1500 suburban 2wd 2008
c1500 suburban 2wd 2008
c1500 suburban 2wd 2008
c1500 suburban 2wd 2008
corvette 2008
corvette 2008
corvette 2008
k1500 tahoe 4wd 2008
k1500 tahoe 4wd 2008
malibu 2008
malibu 2008
malibu 2008
caravan 2wd 2008
caravan 2wd 2008
caravan 2wd 2008
caravan 2wd 2008
caravan 2wd 2008
dakota pickup 4wd 2008
dakota pickup 4wd 2008
dakota pickup 4wd 2008
dakota pickup 4wd 2008
dakota pickup 4wd 2008
durango 4wd 2008
durango 4wd 2008
durango 4wd 2008
durango 4wd 2008
ram 1500 pickup 4wd 2008
ram 1500 pickup 4wd 2008
ram 1500 pickup 4wd 2008
ram 1500 pickup 4wd 2008
ram 1500 pickup 4wd 2008
ram 1500 pickup 4wd 2008
ram 1500 pickup 4wd 2008
expedition 2wd 2008
explorer 4wd 2008
explorer 4wd 2008
f150 pickup 4wd 2008
f150 pickup 4wd 2008
mustang 2008
mustang 2008
mustang 2008
mustang 2008
mustang 2008
civic 2008
civic 2008
civic 2008
civic 2008
sonata 2008
sonata 2008
sonata 2008
tiburon 2008
tiburon 2008
tiburon 2008
tiburon 2008
tiburon 2008
grand cherokee 4wd 2008
grand cherokee 4wd 2008
grand cherokee 4wd 2008
grand cherokee 4wd 2008
grand cherokee 4wd 2008
grand cherokee 4wd 2008
range rover 2008
range rover 2008
navigator 2wd 2008
mountaineer 4wd 2008
mountaineer 4wd 2008
altima 2008
altima 2008
altima 2008
altima 2008
maxima 2008
pathfinder 4wd 2008
pathfinder 4wd 2008
grand prix 2008
grand prix 2008
forester awd 2008
forester awd 2008
forester awd 2008
forester awd 2008
impreza awd 2008
impreza awd 2008
impreza awd 2008
impreza awd 2008
4runner 4wd 2008
4runner 4wd 2008
camry 2008
camry 2008
camry 2008
camry solara 2008
camry solara 2008
camry solara 2008
corolla 2008
corolla 2008
land cruiser wagon 4wd 2008
toyota tacoma 4wd 2008
toyota tacoma 4wd 2008
toyota tacoma 4wd 2008
gti 2008
gti 2008
jetta 2008
jetta 2008
jetta 2008
jetta 2008
new beetle 2008
new beetle 2008
passat 2008
passat 2008
passat 2008

### 카테고리형 변수에 대해서 조건문 만들기

- 'malibu','mustang' 모델들 중 1999과 2008년도 모델만 가지고 오기

In [41]:
car_model = ['malibu','mustang']
car_year = [1999, 2008]
for i, j in zip(mpg.year, mpg.model):
    if i in car_year and j in car_model:
        print(i, j)

1999 malibu
2008 malibu
1999 malibu
2008 malibu
2008 malibu
1999 mustang
1999 mustang
2008 mustang
2008 mustang
1999 mustang
1999 mustang
2008 mustang
2008 mustang
2008 mustang

### 반복문 제공되는 함수들
#### ★ iterrows
-#idx는 인덱스, row는 전체 데이터프레임

In [43]:
for idx, row in mpg.iterrows(): 
    print(idx,row['model'],row['year'])

0 a4 1999
1 a4 1999
2 a4 2008
3 a4 2008
4 a4 1999
5 a4 1999
6 a4 2008
7 a4 quattro 1999
8 a4 quattro 1999
9 a4 quattro 2008
10 a4 quattro 2008
11 a4 quattro 1999
12 a4 quattro 1999
13 a4 quattro 2008
14 a4 quattro 2008
15 a6 quattro 1999
16 a6 quattro 2008
17 a6 quattro 2008
18 c1500 suburban 2wd 2008
19 c1500 suburban 2wd 2008
20 c1500 suburban 2wd 2008
21 c1500 suburban 2wd 1999
22 c1500 suburban 2wd 2008
23 corvette 1999
24 corvette 1999
25 corvette 2008
26 corvette 2008
27 corvette 2008
28 k1500 tahoe 4wd 2008
29 k1500 tahoe 4wd 2008
30 k1500 tahoe 4wd 1999
31 k1500 tahoe 4wd 1999
32 malibu 1999
33 malibu 2008
34 malibu 1999
35 malibu 2008
36 malibu 2008
37 caravan 2wd 1999
38 caravan 2wd 1999
39 caravan 2wd 1999
40 caravan 2wd 1999
41 caravan 2wd 2008
42 caravan 2wd 2008
43 caravan 2wd 2008
44 caravan 2wd 1999
45 caravan 2wd 1999
46 caravan 2wd 2008
47 caravan 2wd 2008
48 dakota pickup 4wd 2008
49 dakota pickup 4wd 2008
50 dakota pickup 4wd 1999
51 dakota pickup 4wd 1999
52 dakota pickup 4wd 2008
53 dakota pickup 4wd 2008
54 dakota pickup 4wd 2008
55 dakota pickup 4wd 1999
56 dakota pickup 4wd 1999
57 durango 4wd 1999
58 durango 4wd 2008
59 durango 4wd 2008
60 durango 4wd 2008
61 durango 4wd 1999
62 durango 4wd 2008
63 durango 4wd 1999
64 ram 1500 pickup 4wd 2008
65 ram 1500 pickup 4wd 2008
66 ram 1500 pickup 4wd 2008
67 ram 1500 pickup 4wd 2008
68 ram 1500 pickup 4wd 2008
69 ram 1500 pickup 4wd 2008
70 ram 1500 pickup 4wd 1999
71 ram 1500 pickup 4wd 1999
72 ram 1500 pickup 4wd 2008
73 ram 1500 pickup 4wd 1999
74 expedition 2wd 1999
75 expedition 2wd 1999
76 expedition 2wd 2008
77 explorer 4wd 1999
78 explorer 4wd 1999
79 explorer 4wd 1999
80 explorer 4wd 2008
81 explorer 4wd 2008
82 explorer 4wd 1999
83 f150 pickup 4wd 1999
84 f150 pickup 4wd 1999
85 f150 pickup 4wd 1999
86 f150 pickup 4wd 1999
87 f150 pickup 4wd 2008
88 f150 pickup 4wd 1999
89 f150 pickup 4wd 2008
90 mustang 1999
91 mustang 1999
92 mustang 2008
93 mustang 2008
94 mustang 1999
95 mustang 1999
96 mustang 2008
97 mustang 2008
98 mustang 2008
99 civic 1999
100 civic 1999
101 civic 1999
102 civic 1999
103 civic 1999
104 civic 2008
105 civic 2008
106 civic 2008
107 civic 2008
108 sonata 1999
109 sonata 1999
110 sonata 2008
111 sonata 2008
112 sonata 1999
113 sonata 1999
114 sonata 2008
115 tiburon 1999
116 tiburon 1999
117 tiburon 2008
118 tiburon 2008
119 tiburon 2008
120 tiburon 2008
121 tiburon 2008
122 grand cherokee 4wd 2008
123 grand cherokee 4wd 2008
124 grand cherokee 4wd 1999
125 grand cherokee 4wd 1999
126 grand cherokee 4wd 2008
127 grand cherokee 4wd 2008
128 grand cherokee 4wd 2008
129 grand cherokee 4wd 2008
130 range rover 1999
131 range rover 2008
132 range rover 2008
133 range rover 1999
134 navigator 2wd 1999
135 navigator 2wd 1999
136 navigator 2wd 2008
137 mountaineer 4wd 1999
138 mountaineer 4wd 2008
139 mountaineer 4wd 2008
140 mountaineer 4wd 1999
141 altima 1999
142 altima 1999
143 altima 2008
144 altima 2008
145 altima 2008
146 altima 2008
147 maxima 1999
148 maxima 1999
149 maxima 2008
150 pathfinder 4wd 1999
151 pathfinder 4wd 1999
152 pathfinder 4wd 2008
153 pathfinder 4wd 2008
154 grand prix 1999
155 grand prix 1999
156 grand prix 1999
157 grand prix 2008
158 grand prix 2008
159 forester awd 1999
160 forester awd 1999
161 forester awd 2008
162 forester awd 2008
163 forester awd 2008
164 forester awd 2008
165 impreza awd 1999
166 impreza awd 1999
167 impreza awd 1999
168 impreza awd 1999
169 impreza awd 2008
170 impreza awd 2008
171 impreza awd 2008
172 impreza awd 2008
173 4runner 4wd 1999
174 4runner 4wd 1999
175 4runner 4wd 1999
176 4runner 4wd 1999
177 4runner 4wd 2008
178 4runner 4wd 2008
179 camry 1999
180 camry 1999
181 camry 2008
182 camry 2008
183 camry 1999
184 camry 1999
185 camry 2008
186 camry solara 1999
187 camry solara 1999
188 camry solara 2008
189 camry solara 2008
190 camry solara 1999
191 camry solara 1999
192 camry solara 2008
193 corolla 1999
194 corolla 1999
195 corolla 1999
196 corolla 2008
197 corolla 2008
198 land cruiser wagon 4wd 1999
199 land cruiser wagon 4wd 2008
200 toyota tacoma 4wd 1999
201 toyota tacoma 4wd 1999
202 toyota tacoma 4wd 2008
203 toyota tacoma 4wd 1999
204 toyota tacoma 4wd 1999
205 toyota tacoma 4wd 2008
206 toyota tacoma 4wd 2008
207 gti 1999
208 gti 1999
209 gti 2008
210 gti 2008
211 gti 1999
212 jetta 1999
213 jetta 1999
214 jetta 1999
215 jetta 2008
216 jetta 2008
217 jetta 2008
218 jetta 2008
219 jetta 1999
220 jetta 1999
221 new beetle 1999
222 new beetle 1999
223 new beetle 1999
224 new beetle 1999
225 new beetle 2008
226 new beetle 2008
227 passat 1999
228 passat 1999
229 passat 2008
230 passat 2008
231 passat 1999
232 passat 1999
233 passat 2008

#### ★ itertuples
- 첫 필드 인덱스, 나머지 열

In [44]:
for row in mpg.itertuples():
    print(row.model, row.year)

a4 1999
a4 1999
a4 2008
a4 2008
a4 1999
a4 1999
a4 2008
a4 quattro 1999
a4 quattro 1999
a4 quattro 2008
a4 quattro 2008
a4 quattro 1999
a4 quattro 1999
a4 quattro 2008
a4 quattro 2008
a6 quattro 1999
a6 quattro 2008
a6 quattro 2008
c1500 suburban 2wd 2008
c1500 suburban 2wd 2008
c1500 suburban 2wd 2008
c1500 suburban 2wd 1999
c1500 suburban 2wd 2008
corvette 1999
corvette 1999
corvette 2008
corvette 2008
corvette 2008
k1500 tahoe 4wd 2008
k1500 tahoe 4wd 2008
k1500 tahoe 4wd 1999
k1500 tahoe 4wd 1999
malibu 1999
malibu 2008
malibu 1999
malibu 2008
malibu 2008
caravan 2wd 1999
caravan 2wd 1999
caravan 2wd 1999
caravan 2wd 1999
caravan 2wd 2008
caravan 2wd 2008
caravan 2wd 2008
caravan 2wd 1999
caravan 2wd 1999
caravan 2wd 2008
caravan 2wd 2008
dakota pickup 4wd 2008
dakota pickup 4wd 2008
dakota pickup 4wd 1999
dakota pickup 4wd 1999
dakota pickup 4wd 2008
dakota pickup 4wd 2008
dakota pickup 4wd 2008
dakota pickup 4wd 1999
dakota pickup 4wd 1999
durango 4wd 1999
durango 4wd 2008
durango 4wd 2008
durango 4wd 2008
durango 4wd 1999
durango 4wd 2008
durango 4wd 1999
ram 1500 pickup 4wd 2008
ram 1500 pickup 4wd 2008
ram 1500 pickup 4wd 2008
ram 1500 pickup 4wd 2008
ram 1500 pickup 4wd 2008
ram 1500 pickup 4wd 2008
ram 1500 pickup 4wd 1999
ram 1500 pickup 4wd 1999
ram 1500 pickup 4wd 2008
ram 1500 pickup 4wd 1999
expedition 2wd 1999
expedition 2wd 1999
expedition 2wd 2008
explorer 4wd 1999
explorer 4wd 1999
explorer 4wd 1999
explorer 4wd 2008
explorer 4wd 2008
explorer 4wd 1999
f150 pickup 4wd 1999
f150 pickup 4wd 1999
f150 pickup 4wd 1999
f150 pickup 4wd 1999
f150 pickup 4wd 2008
f150 pickup 4wd 1999
f150 pickup 4wd 2008
mustang 1999
mustang 1999
mustang 2008
mustang 2008
mustang 1999
mustang 1999
mustang 2008
mustang 2008
mustang 2008
civic 1999
civic 1999
civic 1999
civic 1999
civic 1999
civic 2008
civic 2008
civic 2008
civic 2008
sonata 1999
sonata 1999
sonata 2008
sonata 2008
sonata 1999
sonata 1999
sonata 2008
tiburon 1999
tiburon 1999
tiburon 2008
tiburon 2008
tiburon 2008
tiburon 2008
tiburon 2008
grand cherokee 4wd 2008
grand cherokee 4wd 2008
grand cherokee 4wd 1999
grand cherokee 4wd 1999
grand cherokee 4wd 2008
grand cherokee 4wd 2008
grand cherokee 4wd 2008
grand cherokee 4wd 2008
range rover 1999
range rover 2008
range rover 2008
range rover 1999
navigator 2wd 1999
navigator 2wd 1999
navigator 2wd 2008
mountaineer 4wd 1999
mountaineer 4wd 2008
mountaineer 4wd 2008
mountaineer 4wd 1999
altima 1999
altima 1999
altima 2008
altima 2008
altima 2008
altima 2008
maxima 1999
maxima 1999
maxima 2008
pathfinder 4wd 1999
pathfinder 4wd 1999
pathfinder 4wd 2008
pathfinder 4wd 2008
grand prix 1999
grand prix 1999
grand prix 1999
grand prix 2008
grand prix 2008
forester awd 1999
forester awd 1999
forester awd 2008
forester awd 2008
forester awd 2008
forester awd 2008
impreza awd 1999
impreza awd 1999
impreza awd 1999
impreza awd 1999
impreza awd 2008
impreza awd 2008
impreza awd 2008
impreza awd 2008
4runner 4wd 1999
4runner 4wd 1999
4runner 4wd 1999
4runner 4wd 1999
4runner 4wd 2008
4runner 4wd 2008
camry 1999
camry 1999
camry 2008
camry 2008
camry 1999
camry 1999
camry 2008
camry solara 1999
camry solara 1999
camry solara 2008
camry solara 2008
camry solara 1999
camry solara 1999
camry solara 2008
corolla 1999
corolla 1999
corolla 1999
corolla 2008
corolla 2008
land cruiser wagon 4wd 1999
land cruiser wagon 4wd 2008
toyota tacoma 4wd 1999
toyota tacoma 4wd 1999
toyota tacoma 4wd 2008
toyota tacoma 4wd 1999
toyota tacoma 4wd 1999
toyota tacoma 4wd 2008
toyota tacoma 4wd 2008
gti 1999
gti 1999
gti 2008
gti 2008
gti 1999
jetta 1999
jetta 1999
jetta 1999
jetta 2008
jetta 2008
jetta 2008
jetta 2008
jetta 1999
jetta 1999
new beetle 1999
new beetle 1999
new beetle 1999
new beetle 1999
new beetle 2008
new beetle 2008
passat 1999
passat 1999
passat 2008
passat 2008
passat 1999
passat 1999
passat 2008

In [46]:
for i in range(0,mpg.shape[0]):
    print(mpg.iloc[i])

manufacturer        audi
model                 a4
displ                1.8
year                1999
cyl                    4
trans           auto(l5)
drv                    f
cty                   18
hwy                   29
fl                     p
category         compact
Name: 0, dtype: object
manufacturer          audi
model                   a4
displ                  1.8
year                  1999
cyl                      4
trans           manual(m5)
drv                      f
cty                     21
hwy                     29
fl                       p
category           compact
Name: 1, dtype: object
manufacturer          audi
model                   a4
displ                  2.0
year                  2008
cyl                      4
trans           manual(m6)
drv                      f
cty                     20
hwy                     31
fl                       p
category           compact
Name: 2, dtype: object
manufacturer        audi
model                 a4
displ                2.0
year                2008
cyl                    4
trans           auto(av)
drv                    f
cty                   21
hwy                   30
fl                     p
category         compact
Name: 3, dtype: object
manufacturer        audi
model                 a4
displ                2.8
year                1999
cyl                    6
trans           auto(l5)
drv                    f
cty                   16
hwy                   26
fl                     p
category         compact
Name: 4, dtype: object
manufacturer          audi
model                   a4
displ                  2.8
year                  1999
cyl                      6
trans           manual(m5)
drv                      f
cty                     18
hwy                     26
fl                       p
category           compact
Name: 5, dtype: object
manufacturer        audi
model                 a4
displ                3.1
year                2008
cyl                    6
trans           auto(av)
drv                    f
cty                   18
hwy                   27
fl                     p
category         compact
Name: 6, dtype: object
manufacturer          audi
model           a4 quattro
displ                  1.8
year                  1999
cyl                      4
trans           manual(m5)
drv                      4
cty                     18
hwy                     26
fl                       p
category           compact
Name: 7, dtype: object
manufacturer          audi
model           a4 quattro
displ                  1.8
year                  1999
cyl                      4
trans             auto(l5)
drv                      4
cty                     16
hwy                     25
fl                       p
category           compact
Name: 8, dtype: object
manufacturer          audi
model           a4 quattro
displ                  2.0
year                  2008
cyl                      4
trans           manual(m6)
drv                      4
cty                     20
hwy                     28
fl                       p
category           compact
Name: 9, dtype: object
manufacturer          audi
model           a4 quattro
displ                  2.0
year                  2008
cyl                      4
trans             auto(s6)
drv                      4
cty                     19
hwy                     27
fl                       p
category           compact
Name: 10, dtype: object
manufacturer          audi
model           a4 quattro
displ                  2.8
year                  1999
cyl                      6
trans             auto(l5)
drv                      4
cty                     15
hwy                     25
fl                       p
category           compact
Name: 11, dtype: object
manufacturer          audi
model           a4 quattro
displ                  2.8
year                  1999
cyl                      6
trans           manual(m5)
drv                      4
cty                     17
hwy                     25
fl                       p
category           compact
Name: 12, dtype: object
manufacturer          audi
model           a4 quattro
displ                  3.1
year                  2008
cyl                      6
trans             auto(s6)
drv                      4
cty                     17
hwy                     25
fl                       p
category           compact
Name: 13, dtype: object
manufacturer          audi
model           a4 quattro
displ                  3.1
year                  2008
cyl                      6
trans           manual(m6)
drv                      4
cty                     15
hwy                     25
fl                       p
category           compact
Name: 14, dtype: object
manufacturer          audi
model           a6 quattro
displ                  2.8
year                  1999
cyl                      6
trans             auto(l5)
drv                      4
cty                     15
hwy                     24
fl                       p
category           midsize
Name: 15, dtype: object
manufacturer          audi
model           a6 quattro
displ                  3.1
year                  2008
cyl                      6
trans             auto(s6)
drv                      4
cty                     17
hwy                     25
fl                       p
category           midsize
Name: 16, dtype: object
manufacturer          audi
model           a6 quattro
displ                  4.2
year                  2008
cyl                      8
trans             auto(s6)
drv                      4
cty                     16
hwy                     23
fl                       p
category           midsize
Name: 17, dtype: object
manufacturer             chevrolet
model           c1500 suburban 2wd
displ                          5.3
year                          2008
cyl                              8
trans                     auto(l4)
drv                              r
cty                             14
hwy                             20
fl                               r
category                       suv
Name: 18, dtype: object
manufacturer             chevrolet
model           c1500 suburban 2wd
displ                          5.3
year                          2008
cyl                              8
trans                     auto(l4)
drv                              r
cty                             11
hwy                             15
fl                               e
category                       suv
Name: 19, dtype: object
manufacturer             chevrolet
model           c1500 suburban 2wd
displ                          5.3
year                          2008
cyl                              8
trans                     auto(l4)
drv                              r
cty                             14
hwy                             20
fl                               r
category                       suv
Name: 20, dtype: object
manufacturer             chevrolet
model           c1500 suburban 2wd
displ                          5.7
year                          1999
cyl                              8
trans                     auto(l4)
drv                              r
cty                             13
hwy                             17
fl                               r
category                       suv
Name: 21, dtype: object
manufacturer             chevrolet
model           c1500 suburban 2wd
displ                          6.0
year                          2008
cyl                              8
trans                     auto(l4)
drv                              r
cty                             12
hwy                             17
fl                               r
category                       suv
Name: 22, dtype: object
manufacturer     chevrolet
model             corvette
displ                  5.7
year                  1999
cyl                      8
trans           manual(m6)
drv                      r
cty                     16
hwy                     26
fl                       p
category           2seater
Name: 23, dtype: object
manufacturer    chevrolet
model            corvette
displ                 5.7
year                 1999
cyl                     8
trans            auto(l4)
drv                     r
cty                    15
hwy                    23
fl                      p
category          2seater
Name: 24, dtype: object
manufacturer     chevrolet
model             corvette
displ                  6.2
year                  2008
cyl                      8
trans           manual(m6)
drv                      r
cty                     16
hwy                     26
fl                       p
category           2seater
Name: 25, dtype: object
manufacturer    chevrolet
model            corvette
displ                 6.2
year                 2008
cyl                     8
trans            auto(s6)
drv                     r
cty                    15
hwy                    25
fl                      p
category          2seater
Name: 26, dtype: object
manufacturer     chevrolet
model             corvette
displ                  7.0
year                  2008
cyl                      8
trans           manual(m6)
drv                      r
cty                     15
hwy                     24
fl                       p
category           2seater
Name: 27, dtype: object
manufacturer          chevrolet
model           k1500 tahoe 4wd
displ                       5.3
year                       2008
cyl                           8
trans                  auto(l4)
drv                           4
cty                          14
hwy                          19
fl                            r
category                    suv
Name: 28, dtype: object
manufacturer          chevrolet
model           k1500 tahoe 4wd
displ                       5.3
year                       2008
cyl                           8
trans                  auto(l4)
drv                           4
cty                          11
hwy                          14
fl                            e
category                    suv
Name: 29, dtype: object
manufacturer          chevrolet
model           k1500 tahoe 4wd
displ                       5.7
year                       1999
cyl                           8
trans                  auto(l4)
drv                           4
cty                          11
hwy                          15
fl                            r
category                    suv
Name: 30, dtype: object
manufacturer          chevrolet
model           k1500 tahoe 4wd
displ                       6.5
year                       1999
cyl                           8
trans                  auto(l4)
drv                           4
cty                          14
hwy                          17
fl                            d
category                    suv
Name: 31, dtype: object
manufacturer    chevrolet
model              malibu
displ                 2.4
year                 1999
cyl                     4
trans            auto(l4)
drv                     f
cty                    19
hwy                    27
fl                      r
category          midsize
Name: 32, dtype: object
manufacturer    chevrolet
model              malibu
displ                 2.4
year                 2008
cyl                     4
trans            auto(l4)
drv                     f
cty                    22
hwy                    30
fl                      r
category          midsize
Name: 33, dtype: object
manufacturer    chevrolet
model              malibu
displ                 3.1
year                 1999
cyl                     6
trans            auto(l4)
drv                     f
cty                    18
hwy                    26
fl                      r
category          midsize
Name: 34, dtype: object
manufacturer    chevrolet
model              malibu
displ                 3.5
year                 2008
cyl                     6
trans            auto(l4)
drv                     f
cty                    18
hwy                    29
fl                      r
category          midsize
Name: 35, dtype: object
manufacturer    chevrolet
model              malibu
displ                 3.6
year                 2008
cyl                     6
trans            auto(s6)
drv                     f
cty                    17
hwy                    26
fl                      r
category          midsize
Name: 36, dtype: object
manufacturer          dodge
model           caravan 2wd
displ                   2.4
year                   1999
cyl                       4
trans              auto(l3)
drv                       f
cty                      18
hwy                      24
fl                        r
category            minivan
Name: 37, dtype: object
manufacturer          dodge
model           caravan 2wd
displ                   3.0
year                   1999
cyl                       6
trans              auto(l4)
drv                       f
cty                      17
hwy                      24
fl                        r
category            minivan
Name: 38, dtype: object
manufacturer          dodge
model           caravan 2wd
displ                   3.3
year                   1999
cyl                       6
trans              auto(l4)
drv                       f
cty                      16
hwy                      22
fl                        r
category            minivan
Name: 39, dtype: object
manufacturer          dodge
model           caravan 2wd
displ                   3.3
year                   1999
cyl                       6
trans              auto(l4)
drv                       f
cty                      16
hwy                      22
fl                        r
category            minivan
Name: 40, dtype: object
manufacturer          dodge
model           caravan 2wd
displ                   3.3
year                   2008
cyl                       6
trans              auto(l4)
drv                       f
cty                      17
hwy                      24
fl                        r
category            minivan
Name: 41, dtype: object
manufacturer          dodge
model           caravan 2wd
displ                   3.3
year                   2008
cyl                       6
trans              auto(l4)
drv                       f
cty                      17
hwy                      24
fl                        r
category            minivan
Name: 42, dtype: object
manufacturer          dodge
model           caravan 2wd
displ                   3.3
year                   2008
cyl                       6
trans              auto(l4)
drv                       f
cty                      11
hwy                      17
fl                        e
category            minivan
Name: 43, dtype: object
manufacturer          dodge
model           caravan 2wd
displ                   3.8
year                   1999
cyl                       6
trans              auto(l4)
drv                       f
cty                      15
hwy                      22
fl                        r
category            minivan
Name: 44, dtype: object
manufacturer          dodge
model           caravan 2wd
displ                   3.8
year                   1999
cyl                       6
trans              auto(l4)
drv                       f
cty                      15
hwy                      21
fl                        r
category            minivan
Name: 45, dtype: object
manufacturer          dodge
model           caravan 2wd
displ                   3.8
year                   2008
cyl                       6
trans              auto(l6)
drv                       f
cty                      16
hwy                      23
fl                        r
category            minivan
Name: 46, dtype: object
manufacturer          dodge
model           caravan 2wd
displ                   4.0
year                   2008
cyl                       6
trans              auto(l6)
drv                       f
cty                      16
hwy                      23
fl                        r
category            minivan
Name: 47, dtype: object
manufacturer                dodge
model           dakota pickup 4wd
displ                         3.7
year                         2008
cyl                             6
trans                  manual(m6)
drv                             4
cty                            15
hwy                            19
fl                              r
category                   pickup
Name: 48, dtype: object
manufacturer                dodge
model           dakota pickup 4wd
displ                         3.7
year                         2008
cyl                             6
trans                    auto(l4)
drv                             4
cty                            14
hwy                            18
fl                              r
category                   pickup
Name: 49, dtype: object
manufacturer                dodge
model           dakota pickup 4wd
displ                         3.9
year                         1999
cyl                             6
trans                    auto(l4)
drv                             4
cty                            13
hwy                            17
fl                              r
category                   pickup
Name: 50, dtype: object
manufacturer                dodge
model           dakota pickup 4wd
displ                         3.9
year                         1999
cyl                             6
trans                  manual(m5)
drv                             4
cty                            14
hwy                            17
fl                              r
category                   pickup
Name: 51, dtype: object
manufacturer                dodge
model           dakota pickup 4wd
displ                         4.7
year                         2008
cyl                             8
trans                    auto(l5)
drv                             4
cty                            14
hwy                            19
fl                              r
category                   pickup
Name: 52, dtype: object
manufacturer                dodge
model           dakota pickup 4wd
displ                         4.7
year                         2008
cyl                             8
trans                    auto(l5)
drv                             4
cty                            14
hwy                            19
fl                              r
category                   pickup
Name: 53, dtype: object
manufacturer                dodge
model           dakota pickup 4wd
displ                         4.7
year                         2008
cyl                             8
trans                    auto(l5)
drv                             4
cty                             9
hwy                            12
fl                              e
category                   pickup
Name: 54, dtype: object
manufacturer                dodge
model           dakota pickup 4wd
displ                         5.2
year                         1999
cyl                             8
trans                  manual(m5)
drv                             4
cty                            11
hwy                            17
fl                              r
category                   pickup
Name: 55, dtype: object
manufacturer                dodge
model           dakota pickup 4wd
displ                         5.2
year                         1999
cyl                             8
trans                    auto(l4)
drv                             4
cty                            11
hwy                            15
fl                              r
category                   pickup
Name: 56, dtype: object
manufacturer          dodge
model           durango 4wd
displ                   3.9
year                   1999
cyl                       6
trans              auto(l4)
drv                       4
cty                      13
hwy                      17
fl                        r
category                suv
Name: 57, dtype: object
manufacturer          dodge
model           durango 4wd

- 컬럼 기반으로 접근하기
- 컬럼의 데이터 타입에 따라 출력가능하다.

In [47]:
for i in mpg:
    print(i)

manufacturer
model
displ
year
cyl
trans
drv
cty
hwy
fl
category

In [48]:
mpg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   manufacturer  234 non-null    object
 1   model         234 non-null    object
 2   displ         234 non-null    float64
 3   year          234 non-null    int64
 4   cyl           234 non-null    int64
 5   trans         234 non-null    object
 6   drv           234 non-null    object
 7   cty           234 non-null    int64
 8   hwy           234 non-null    int64
 9   fl            234 non-null    object
 10  category      234 non-null    object
dtypes: float64(1), int64(4), object(6)
memory usage: 20.2+ KB

In [50]:
for hh in mpg.columns:
    df_coltp = str(mpg[hh].dtype)
    if df_coltp == 'object':
        print(hh, 'object')
    else:
        print(hh,'else')

manufacturer object
model object
displ else
year else
cyl else
trans object
drv object
cty else
hwy else
fl object
category object

In [51]:
for hh in mpg.columns:
    df_coltp = str(mpg[hh].dtype)
    if df_coltp =='object':
        print(hh, mpg[hh].value_counts())
    else:
        print(hh,mpg[hh].describe())

manufacturer dodge         37
toyota        34
volkswagen    27
ford          25
chevrolet     19
audi          18
hyundai       14
subaru        14
nissan        13
honda          9
jeep           8
pontiac        5
land rover     4
mercury        4
lincoln        3
Name: manufacturer, dtype: int64
model caravan 2wd               11
ram 1500 pickup 4wd       10
civic                      9
jetta                      9
dakota pickup 4wd          9
mustang                    9
impreza awd                8
a4 quattro                 8
grand cherokee 4wd         8
a4                         7
toyota tacoma 4wd          7
camry solara               7
camry                      7
tiburon                    7
sonata                     7
passat                     7
f150 pickup 4wd            7
durango 4wd                7
explorer 4wd               6
new beetle                 6
altima                     6
4runner 4wd                6
forester awd               6
gti                        5
c1500 suburban 2wd         5
corolla                    5
corvette                   5
malibu                     5
grand prix                 5
k1500 tahoe 4wd            4
pathfinder 4wd             4
mountaineer 4wd            4
range rover                4
maxima                     3
navigator 2wd              3
a6 quattro                 3
expedition 2wd             3
land cruiser wagon 4wd     2
Name: model, dtype: int64
displ count    234.000000
mean       3.471795
std        1.291959
min        1.600000
25%        2.400000
50%        3.300000
75%        4.600000
max        7.000000
Name: displ, dtype: float64
year count     234.000000
mean     2003.500000
std         4.509646
min      1999.000000
25%      1999.000000
50%      2003.500000
75%      2008.000000
max      2008.000000
Name: year, dtype: float64
cyl count    234.000000
mean       5.888889
std        1.611534
min        4.000000
25%        4.000000
50%        6.000000
75%        8.000000
max        8.000000
Name: cyl, dtype: float64
trans auto(l4)      83
manual(m5)    58
auto(l5)      39
manual(m6)    19
auto(s6)      16
auto(l6)       6
auto(av)       5
auto(s5)       3
auto(s4)       3
auto(l3)       2
Name: trans, dtype: int64
drv f    106
4    103
r     25
Name: drv, dtype: int64
cty count    234.000000
mean      16.858974
std        4.255946
min        9.000000
25%       14.000000
50%       17.000000
75%       19.000000
max       35.000000
Name: cty, dtype: float64
hwy count    234.000000
mean      23.440171
std        5.954643
min       12.000000
25%       18.000000
50%       24.000000
75%       27.000000
max       44.000000
Name: hwy, dtype: float64
fl r    168
p     52
e      8
d      5
c      1
Name: fl, dtype: int64
category suv           62
compact       47
midsize       41
subcompact    35
pickup        33
minivan       11
2seater        5
Name: category, dtype: int64

- 시리즈 형태로 반복문 이용해 조건물을 더욱 정교하게 만들자
- mpg 데이터 중에서 trans 변수에 s6 값 있는 데이터를 출력하여 제조사별 카운팅
- l5만 추출하는 함수를 만들어보자

In [52]:
mpg

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,category
0,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact
1,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact
2,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact
3,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact
4,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact
...,...,...,...,...,...,...,...,...,...,...,...
229,volkswagen,passat,2.0,2008,4,auto(s6),f,19,28,p,midsize
230,volkswagen,passat,2.0,2008,4,manual(m6),f,21,29,p,midsize
231,volkswagen,passat,2.8,1999,6,auto(l5),f,16,26,p,midsize
232,volkswagen,passat,2.8,1999,6,manual(m5),f,18,26,p,midsize
233,volkswagen,passat,3.6,2008,6,auto(s6),f,17,26,p,midsize

In [72]:
def get_trans_spe(series):
    tr_hh = len([_ for x in series if x[0] in 'm5'])
    return tr_hh

- 제조사별 카운팅해야함

In [73]:
get_trans_spe(mpg.trans)

77

In [74]:
mpg.groupby('manufacturer').agg({'trans':get_trans_spe}).reset_index()

   manufacturer  trans
0          audi      7
1     chevrolet      3
2         dodge      7
3          ford      8
4         honda      5
5       hyundai      7
6          jeep      0
7    land rover      0
8       lincoln      0
9       mercury      0
10       nissan      5
11      pontiac      0
12       subaru      7
13       toyota     14
14   volkswagen     14

- 연도별로 cty 평균이 16미만 친구들과 16이상이 친구들을 묶어보자!

In [75]:
def get_y_cty(series):
    if mpg.iloc[series.index[0], : ]['year']==2008:
        cty_cnt = len([_ for x in series if x>=16])
    else:
        cty_cnt = len([_ for x in series if x<16])
    return cty_cnt

In [76]:
mpg.groupby('year').agg({'cty':get_y_cty}).reset_index()

   year  cty
0  1999   48
1  2008   68

### 데이터를 나눌 수 있다.
- cut 함수를 사용하여 원하는 값의 구간별로 레이블을 넣어서 전처리 할 수 있다.

In [79]:
pd.cut(mpg['hwy'], bins = [10,15,20,25], labels= ['bad','good','very good']).describe()

count      133
unique       3
top       good
freq        72
Name: hwy, dtype: object